BOARD = teensy31
F_CPU = 96000000

# this is the default for teensy
#USE_LAYOUT = LAYOUT_US_ENGLISH
#LAYOUT_US_ENGLISH
#LAYOUT_CANADIAN_FRENCH
#LAYOUT_CANADIAN_MULTILINGUAL
#LAYOUT_DANISH
#LAYOUT_FINNISH
#LAYOUT_FRENCH
#LAYOUT_FRENCH_BELGIAN
#LAYOUT_FRENCH_SWISS
#LAYOUT_GERMAN
#LAYOUT_GERMAN_MAC
#LAYOUT_GERMAN_SWISS
#LAYOUT_ICELANDIC
#LAYOUT_IRISH
#LAYOUT_ITALIAN
#LAYOUT_NORWEGIAN
#LAYOUT_PORTUGUESE
#LAYOUT_PORTUGUESE_BRAZILIAN
#LAYOUT_SPANISH
#LAYOUT_SPANISH_LATIN_AMERICA
#LAYOUT_SWEDISH
#LAYOUT_TURKISH
#LAYOUT_UNITED_KINGDOM
#LAYOUT_US_INTERNATIONAL

# set your Arduino tty port here
PORT = /dev/ttyACM0


#USB_BUILD_DEFINE = USB_RAWHID
USB_BUILD_DEFINE = USB_CUSTOM
# And finally, the part that brings everything together for you.
include ../Arduino_Makefile_master/_Makefile.master
